### ISSUE TITLE
Is it possible to insert link with the footnote?

### ISSUE THREAD

**Issue by yansusanto** [KittyGiraudel/site#65]
```
Something about {% footnoteref "css-counters" "[CSS counters](https://example.com) are, in
essence, variables maintained by CSS whose values may be
incremented by CSS rules to track how many times they’re used." %}
CSS counters{% endfootnoteref %} that deserves a footnote explaining
what they are.
```

Apparently, it doesn't render the link, does it not?

**Comment by KittyGiraudel** [comment]
Hello! I assume you’re referring to [eleventy-plugin-footnotes](https://github.com/KittyGiraudel/eleventy-plugin-footnotes)? The example section explains how to use Markdown in footnotes: https://github.com/KittyGiraudel/eleventy-plugin-footnotes#example

**Comment by yansusanto** [comment]
Thanks for your response. I did.

```
{% assign CCMA_footnote = "Please [click on the region](http://dhr.alabama.gov/counties/daycare_agency.aspx) you desire to obtain information about the appropriate Child Care Management Agency.", "" %}

If you think you’re income eligible, you must download and complete the Child Care Assistance Application form and mail it to your local {% footnoteref "CCMA" CCMA_footnote %}Child Care Management Agency{% endfootnoteref %}.

```

But apparently, it renders

Please [click on the region](http://dhr.alabama.gov/counties/daycare_agency.aspx) you desire to obtain information about the appropriate Child Care Management Agency. ↩

**Comment by KittyGiraudel** [comment]
Right, but you’re not parsing the content of your footnote as Markdown. It’s not enough to just store it in a variable, you also need to actually parse the content as Markdown so that when it’s injected as a footnote, it’s already HTML and not Markdown anymore.

For instance:

```liquid
{% assign content = "My [content](https://google.com)" | markdown | replace: "<p>", "" | replace: "</p>", "" %}
```

The `markdown` filter is not a native Liquid filter unfortunately, so you’ll have to author it yourself in your 11ty configuration. Here is how I did it: https://github.com/KittyGiraudel/site/blob/main/.eleventy.js#L42

**Comment by yansusanto** [comment]
Thank you and sorry for being noob. If the article is written in Markdown, do I still need to parse the content as Markdown? Kinda confused.

But anyway I tried to add the filter and used your example, I've got `markdown is not defined` eventhough I have added the config in my eleventy.js.
```
{% assign content = "My [content](https://google.com)" | markdown | replace: "<p>", "" | replace: "</p>", "" %}
```

**Comment by KittyGiraudel** [comment]
> If the article is written in Markdown, do I still need to parse the content as Markdown? Kinda confused.

Yes, because this variable assignment is just a string. It’s not parsed as Markdown. It’s treated as authored, as a string.

> If the article is written in Markdown, do I still need to parse the content as Markdown? Kinda confused.

It seems that you added the filter to your configuration like I did in mine, but you didn’t actually define the markdown function. That’s not a templating error, that’s a JavaScript error. Your configurations is invalid. You need to author the function to parse Markdown content. In my case, this is my function:

https://github.com/KittyGiraudel/site/blob/e9f12a3b24f90ba8aa3637cdbc8e255a64fe6bf4/.eleventy.js#L115-L119

And it relies on [markdown-it](https://github.com/markdown-it/markdown-it), so the library needs to be installed and imported as well.

**Comment by yansusanto** [comment]
Thank you very much for your patience, my friend. That works! Appreciate your time. Have a good day ahead.

**Comment by KittyGiraudel** [comment]
No worries, take care!
